% crate the network composed of N_POP populations of
% N_NEURONS neurons implementing a SOM
% and init each struct weight and activity matrices
function populations = create_init_network(N_POP, N_NEURONS)
    wcross = rand(N_NEURONS, N_NEURONS, N_POP-1);
    sigma_def = 0.045000;
    for pop_idx = 1:N_POP
        populations(pop_idx) = struct(...
            'idx', pop_idx, ...
            'lsize', N_NEURONS, ...
            'Winput', 0.00001*rand(N_NEURONS, 1), ...
            's', sigma_def*ones(N_NEURONS, 1),...
            'Wcross1', wcross(:,:,1)./sum(wcross(:)), ...
            'Wcross2', wcross(:,:,2)./sum(wcross(:)), ...
            'a', zeros(N_NEURONS, 1));
    end
end